-- Infistyle India Product Catalog Seed
-- Run this in your Supabase SQL Editor after creating the schema

-- Clear existing products first
truncate table public.products cascade;

-- Insert Visiting Cards
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Standard Visiting Cards', 'standard-visiting-cards', 'Visiting Cards', 200.00, 
  array['Standard 3.5" x 2.0" size', 'Glossy or matte finish', '350 GSM premium cardstock', 'Double-sided printing available'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Standard Glossy"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500, 1000]}'::jsonb),
('Classic Visiting Cards', 'classic-visiting-cards', 'Visiting Cards', 250.00,
  array['Classic texture options', 'Sturdy 400 GSM cardstock', 'Professional look & feel', 'Perfect for executive networking'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Standard Glossy", "Premium Matte Laminated"], "corners": ["Square"], "quantities": [100, 200, 500]}'::jsonb),
('Rounded Corner Cards', 'rounded-corner-visiting-cards', 'Visiting Cards', 300.00,
  array['Quarter-inch rounded corners', 'Prevents frayed edges', 'Modern and distinct appearance', 'Premium laminate coating'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Premium Matte Laminated", "Premium Glossy Laminated"], "corners": ["Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Square Visiting Cards', 'square-visiting-cards', 'Visiting Cards', 280.00,
  array['Unique 2.5" x 2.5" square layout', 'Modern aesthetic', 'Stands out in card holders', 'Heavy cardstock feel'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Premium Matte Laminated"], "corners": ["Square"], "quantities": [100, 200, 500]}'::jsonb),
('Leaf Visiting Cards', 'leaf-visiting-cards', 'Visiting Cards', 350.00,
  array['Elegant leaf-shaped die cut', 'Perfect for wellness & nature brands', 'Premium touch-sensitive finish', 'Unique conversation starter'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Matte Laminated"], "corners": ["Leaf Cut"], "quantities": [100, 200, 500]}'::jsonb),
('Oval Visiting Cards', 'oval-visiting-cards', 'Visiting Cards', 350.00,
  array['Smooth oval shape', 'High visual impact', 'Scratch-resistant lamination', 'Elegant and memorable design'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Matte Laminated", "Premium Glossy Laminated"], "corners": ["Oval Cut"], "quantities": [100, 200, 500]}'::jsonb),
('Circle Visiting Cards', 'circle-visiting-cards', 'Visiting Cards', 350.00,
  array['Round 2.5" diameter circle design', 'Creative agency favorite', 'High durability paper', 'Vibrant printing output'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Premium Glossy Laminated"], "corners": ["Circular"], "quantities": [100, 200, 500]}'::jsonb),
('QR Code Visiting Cards', 'qr-code-visiting-cards', 'Visiting Cards', 240.00,
  array['Integrated QR code template', 'Direct scan to contact/vCard', 'High scan-rate matte finish', 'Seamless offline-to-digital transition'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Premium Matte Laminated"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Spot UV Visiting Cards', 'spot-uv-visiting-cards', 'Visiting Cards', 450.00,
  array['Raised gloss lacquer on specific elements', 'High tactile contrast', 'Luxurious velvet base lamination', 'Exquisite brand presentation'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Velvet Laminated + Spot UV"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Raised Foil Visiting Cards', 'raised-foil-visiting-cards', 'Visiting Cards', 500.00,
  array['Stunning metallic gold or silver foil', 'Raised texture you can feel', 'Super premium velvet feel paper', 'Designed to make an impression'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Velvet Laminated + Gold Foil", "Premium Velvet Laminated + Silver Foil"], "corners": ["Square"], "quantities": [100, 200, 500]}'::jsonb),
('Glossy Visiting Cards', 'glossy-visiting-cards', 'Visiting Cards', 180.00,
  array['High-gloss UV protective coating', 'Vibrant photo-realistic color print', 'Heavy weight cardstock', 'Affordable luxury packaging'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Glossy"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500, 1000]}'::jsonb),
('Matte Visiting Cards', 'matte-visiting-cards', 'Visiting Cards', 190.00,
  array['Sleek matte glare-free finish', 'Smooth surface for writing notes', 'Classic understated style', 'Durable build quality'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500, 1000]}'::jsonb),
('Bulk Visiting Cards', 'bulk-visiting-cards', 'Visiting Cards', 1000.00,
  array['Cost-effective solution for whole teams', 'High-volume printing batches', 'Consistent color matching', 'Durable utility cardstock'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Standard Glossy"], "corners": ["Square"], "quantities": [1000, 2000, 5000]}'::jsonb),
('Magnetic Visiting Cards', 'magnetic-visiting-cards', 'Visiting Cards', 600.00,
  array['Fully magnetic back sheet', 'Ideal for refrigerators & cabinets', 'Keeps your contacts permanently visible', 'Gloss water-resistant front'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Glossy Magnetic"], "corners": ["Square"], "quantities": [50, 100, 200]}'::jsonb),
('Transparent Visiting Cards', 'transparent-visiting-cards', 'Visiting Cards', 550.00,
  array['Frosted transparent plastic', 'Modern tech-forward style', 'Waterproof and tearproof', 'Unique white ink layer support'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Frosted Plastic Transparent"], "corners": ["Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Premium Plus Visiting Cards', 'premium-plus-visiting-cards', 'Visiting Cards', 400.00,
  array['Extra thick 450 GSM luxury card', 'Soft-touch lamination', 'Elite feel for executives', 'Scratch resistant coating'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Velvet Laminated"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Non-Tearable Visiting Cards', 'non-tearable-visiting-cards', 'Visiting Cards', 380.00,
  array['Synthetic tear-resistant paper', '100% waterproof and durable', 'Wipeable surface', 'Resists oil and dirt stains'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Tearproof Matte Finish"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Velvet Touch Visiting Cards', 'velvet-touch-visiting-cards', 'Visiting Cards', 420.00,
  array['Soft suede-like feel', 'Extraordinary tactile quality', 'Rich color saturation', 'Heavy card base'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Velvet Laminated"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Pearl Visiting Cards', 'pearl-visiting-cards', 'Visiting Cards', 460.00,
  array['Shimmering metallic pearl paper', 'Adds a subtle glitter glow', 'Perfect for jewelry and fashion brands', 'Elegant luxury texture'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Shimmering Pearl Finish"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Kraft Visiting Cards', 'kraft-visiting-cards', 'Visiting Cards', 320.00,
  array['Eco-friendly brown kraft paper', 'Organic rustic style', '100% recycled fibers', 'Distinct dark fiber inclusions'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Natural Kraft Paper"], "corners": ["Square", "Rounded"], "quantities": [100, 200, 500]}'::jsonb),
('Diamond Visiting Cards', 'diamond-visiting-cards', 'Visiting Cards', 480.00,
  array['Sophisticated diamond pattern texture', 'Embossed structure feel', 'Exclusive corporate card', 'Rigid heavy board base'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Textured Diamond Board"], "corners": ["Square"], "quantities": [100, 200, 500]}'::jsonb),
('Metal Card Holders', 'metal-card-holders', 'Visiting Cards', 350.00,
  array['Polished stainless steel casing', 'Sleek laser engraving option', 'Fits up to 15 business cards', 'Pocket friendly and robust'],
  array['https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80'],
  '{"materials": ["Stainless Steel", "Matte Black Metal"], "quantities": [1, 2, 5, 10]}'::jsonb);

-- Insert Stationery, Letterheads & Notebooks
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Letterheads', 'letterheads', 'Stationery', 450.00,
  array['A4 premium executive bonding paper', '100 GSM and 120 GSM options', 'Laser-printer compatible', 'Vibrant company logo colors'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["100 GSM Bond Paper", "120 GSM Executive Paper"], "quantities": [100, 250, 500, 1000]}'::jsonb),
('Letterhead Pads', 'letterhead-pads', 'Stationery', 600.00,
  array['Top-glued tearable pads', '50 sheets per pad', 'Sturdy cardboard back support', 'Perfect for desk correspondence'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["100 GSM Bond Paper"], "quantities": [5, 10, 25, 50]}'::jsonb),
('Bill Books', 'bill-books', 'Stationery', 550.00,
  array['Duplicate or triplicate NCR carbonless', 'Consecutive serial numbering', 'Cardboard separator insert', 'Perforated copy sheets'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Duplicate (NCR)", "Triplicate (NCR)"], "quantities": [10, 20, 50]}'::jsonb),
('Envelopes', 'envelopes', 'Stationery', 400.00,
  array['A4 and DL sizes available', 'Self-adhesive peel & seal strip', '100 GSM premium maplitho paper', 'Full face branding option'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["DL Envelope", "A4 Envelope"], "quantities": [100, 250, 500]}'::jsonb),
('Custom Mouse Pads', 'custom-mouse-pads', 'Stationery', 180.00,
  array['High density rubber base', 'Smooth fabric tracking surface', 'Washable non-fade print', 'Anti-fray stitched borders'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"shapes": ["Standard Rectangular", "Ergonomic Gel Rest"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Laptop Skins', 'laptop-skins', 'Stationery', 250.00,
  array['Premium bubble-free vinyl', 'Scratch resistant matte laminate', 'Removable leaves no sticky residue', 'Gridlines on back for easy trim'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["15.6 inch Laptop", "14 inch Laptop", "MacBook Pro"], "quantities": [1, 2, 5]}'::jsonb),
('Lanyards', 'lanyards', 'Stationery', 80.00,
  array['Satin finish smooth polyester', 'All-around vivid color print', 'Metal dog hook & safety breakaway', 'Multi-width option (16mm, 20mm)'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"widths": ["16mm Width", "20mm Width"], "quantities": [50, 100, 250, 500]}'::jsonb),
('ID Cards', 'id-cards', 'Stationery', 120.00,
  array['Durable rigid PVC plastic', 'Credit card thickness (760 microns)', 'High definition print overlay', 'Single or double-sided print'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Glossy PVC", "Matte PVC"], "quantities": [10, 25, 50, 100]}'::jsonb),
('Invoice Books', 'invoice-books', 'Stationery', 550.00,
  array['Carbonless copy pages', 'Perforated customer copy pages', 'Bound in clean book format', 'Custom serial numbering'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Duplicate", "Triplicate"], "quantities": [10, 20, 50]}'::jsonb),
('Note Cards', 'note-cards', 'Stationery', 300.00,
  array['Custom sized small message cards', 'Perfect for personal client notes', '350 GSM premium matte board', 'Includes blank white envelopes'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Natural Kraft"], "quantities": [50, 100, 200]}'::jsonb),
('Certificates', 'certificates', 'Stationery', 450.00,
  array['A4 premium textured card', 'Ideal for graduation & appreciation', 'Metallic foil stamp option', 'High fidelity color rendering'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Textured Card", "Parchment Art Card"], "quantities": [10, 25, 50, 100]}'::jsonb),
('Personalised Notebooks', 'personalised-notebooks', 'Stationery', 290.00,
  array['Wire-O spiral bound notebook', 'Custom photo/logo printed cover', '80 inner ruled sheets (160 pages)', 'High grade 80 GSM maplitho inside'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["A5 Notebook", "A4 Notebook"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Diary with Pen Holder', 'diary-with-pen-holder', 'Stationery', 390.00,
  array['Leatherette premium cover finish', 'Elastic pen loop and bookmark ribbon', 'Ruled pages with daily planner', 'Vibrant emboss or foil deboss logo'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Matte Black Leatherette", "Tan Brown Leatherette"], "quantities": [1, 10, 25, 100]}'::jsonb),
('A5 Diary', 'a5-diary', 'Stationery', 320.00,
  array['Standard A5 planner layout', 'Weekly and daily page grids', 'Custom cover branding page', 'High-quality binding'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Hardcover Matte", "Softcover Flexi"], "quantities": [1, 5, 20, 100]}'::jsonb),
('Wedding Invitations', 'wedding-invitations', 'Stationery', 800.00,
  array['Luxurious pearl shimmer papers', 'Intricate die cut borders', 'Comes with matching theme envelopes', 'Foil details in rose gold & gold'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Pearl Shimmer + Gold Foil", "Premium Textured Matte"], "quantities": [50, 100, 200]}'::jsonb),
('Save The Date', 'save-the-date', 'Stationery', 400.00,
  array['Creative layouts (cards / magnets)', 'Vivid photo printing', 'High thickness cardstock', 'Custom designer themes'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Matte Card", "Magnetic Photo Card"], "quantities": [50, 100, 200]}'::jsonb),
('Thank You Cards', 'thank-you-cards', 'Stationery', 350.00,
  array['Elegant folded or flat card design', 'Includes envelopes', 'Adds a premium touch to retail orders', 'Writable inner pages'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Natural Recycled Kraft", "Premium Smooth Matte"], "quantities": [50, 100, 500]}'::jsonb),
('Presentation Folders', 'presentation-folders', 'Stationery', 950.00,
  array['Holds A4 document sheets', 'Built-in business card slits', 'Dual pocket document fold', 'Fully laminated glossy exterior'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Glossy Laminated", "Premium Matte Laminated"], "quantities": [100, 250, 500]}'::jsonb),
('Keychains', 'keychains', 'Stationery', 90.00,
  array['Premium clear acrylic or metal base', 'Double-sided scratchproof print', 'Chrome split ring attachment', 'Custom shapes available'],
  array['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80'],
  '{"materials": ["Acrylic Double-sided", "Engraved Metal"], "quantities": [25, 50, 100, 250]}'::jsonb);

-- Insert Stamps and Ink
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Self Inking Stamps', 'self-inking-stamps', 'Stamps', 320.00,
  array['Built-in replaceable ink pad', '10,000+ crisp impressions', 'Compact plastic casing', 'Available in Blue, Black, Red'],
  array['https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80'],
  '{"ink_colors": ["Black", "Blue", "Red"], "sizes": ["Small (Round)", "Medium (Rectangular)"], "quantities": [1, 2, 5]}'::jsonb),
('Basic Rubber Stamps', 'basic-rubber-stamps', 'Stamps', 150.00,
  array['Traditional wooden handle stamp', 'Durable vulcanized rubber sheet', 'Needs external ink pad', 'Eco-friendly wood material'],
  array['https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["Standard (Rectangular)", "Pocket Size"], "quantities": [1, 2, 5]}'::jsonb),
('Pocket Stamps', 'pocket-stamps', 'Stamps', 280.00,
  array['Folding portable pocket stamp', 'Built-in ink chamber', 'No-mess closing cap', 'Ideal for doctors & field agents'],
  array['https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80'],
  '{"ink_colors": ["Black", "Blue"], "quantities": [1, 2, 5]}'::jsonb),
('Name Stamps', 'name-stamps', 'Stamps', 220.00,
  array['Single-line or double-line layout', 'Sleek design housing', 'Quick drying ink formula', 'Easy alignment window'],
  array['https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80'],
  '{"ink_colors": ["Black", "Blue"], "quantities": [1, 2, 5]}'::jsonb),
('Paper Embosser', 'paper-embosser', 'Stamps', 1200.00,
  array['Creates clean raised 3D textures', 'No ink needed', 'Heavy duty steel mechanism', 'Perfect for official seals & notarials'],
  array['https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["Standard (Round 40mm)"], "quantities": [1]}'::jsonb);

-- Insert Signs, Posters & Marketing Materials
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Flyers', 'flyers', 'Signs', 450.00,
  array['A5 and A4 single/double-sided', '130 GSM glossy art paper', 'Crisp high speed color run', 'Affordable promotional item'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["A5 Size", "A4 Size"], "finishes": ["Standard Glossy", "Standard Matte"], "quantities": [100, 250, 500, 1000]}'::jsonb),
('Posters', 'posters', 'Signs', 120.00,
  array['Large format high-res printing', 'A3, A2, and A1 size choices', '220 GSM photo paper', 'Non-fade UV inks used'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["A3 Size", "A2 Size", "A1 Size"], "finishes": ["Premium Glossy", "Premium Matte"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Banners', 'banners', 'Signs', 800.00,
  array['Durable outdoor flex/star banner', 'Weatherproof brass eyelets included', 'Reinforced hemmed margins', 'Sun-resistant vibrant inks'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["6x3 Feet Banner", "8x4 Feet Banner"], "quantities": [1, 2, 5]}'::jsonb),
('Standees', 'standees', 'Signs', 1800.00,
  array['Retractable aluminum stand pull-up', 'Premium non-tearable flex media', 'Comes with carry bag', 'Folds away in seconds'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["6x3 Feet Standee"], "quantities": [1, 2, 5]}'::jsonb),
('Brochures', 'brochures', 'Signs', 1500.00,
  array['Bi-fold or Tri-fold configuration', '170 GSM thick art paper', 'Precision scoring and folding', 'Glossy UV shield coat'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"folds": ["Bi-fold (4 pages)", "Tri-fold (6 pages)"], "quantities": [100, 250, 500]}'::jsonb),
('Pamphlets', 'pamphlets', 'Signs', 350.00,
  array['Simple lightweight handouts', '90 GSM maplitho paper', 'Clear text readability', 'Budget bulk advertising'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["A5 Size", "A4 Size"], "quantities": [500, 1000, 2500]}'::jsonb),
('Danglers', 'danglers', 'Signs', 450.00,
  array['Eye-catching retail hanging signs', '350 GSM stiff card double-sided', 'Comes with attached thread/string', 'Circle, square or star shapes'],
  array['https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&w=600&q=80'],
  '{"shapes": ["Square Dangler", "Circular Dangler"], "quantities": [50, 100, 250]}'::jsonb;

-- Insert Labels, Stickers & Packaging
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Sheet Stickers', 'sheet-stickers', 'Stickers', 250.00,
  array['Multiple sticker cuts per sheet', 'Glossy water-resistant vinyl', 'Easy peel kiss-cut lines', 'Perfect for products & labels'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Glossy", "Premium Matte Laminated"], "quantities": [10, 25, 50]}'::jsonb),
('Custom Shape Stickers', 'custom-shape-stickers', 'Stickers', 350.00,
  array['Die-cut to exact shape outline', 'Premium thick vinyl shielding', 'Sunlight & waterproof layer', 'Leaves no residue'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Glossy", "Premium Matte"], "quantities": [50, 100, 250]}'::jsonb),
('Sticker Singles', 'sticker-singles', 'Stickers', 280.00,
  array['Individually cut promo stickers', 'Sturdy card backing liner', 'Vibrant digital laser printing', 'Popular for tech giveaways'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Glossy"], "quantities": [50, 100, 250]}'::jsonb),
('Window Stickers', 'window-stickers', 'Stickers', 450.00,
  array['Front or back cling adhesive', 'Apply to glass windows inside/outside', 'Semi-transparent or solid white backing', 'UV-shielded no fading'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"types": ["Front Adhesive Cling", "Back Adhesive Vinyl"], "quantities": [5, 10, 25]}'::jsonb),
('QR Code Stickers', 'qr-code-stickers', 'Stickers', 260.00,
  array['Pre-rendered high-contrast codes', 'Ideal for table service or app installs', 'Durable scratch-proof coating', 'Available on sheets or rolls'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte"], "quantities": [50, 100, 250]}'::jsonb),
('Self Adhesive Tapes', 'self-adhesive-tapes', 'Stickers', 600.00,
  array['Custom logo printed packing tape', 'High strength adhesive bond', 'Standard 2 inch width rolls', 'Eco kraft paper tape option'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"materials": ["BOPP Plastic Tape", "Eco Kraft Paper Tape"], "quantities": [6, 12, 24]}'::jsonb),
('Custom Paper Bags', 'custom-paper-bags', 'Stickers', 800.00,
  array['Eco recycled kraft paper', 'Sturdy twisted paper handles', 'Reinforced cardboard base', 'Holds up to 5kg load'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["Medium Paper Bag", "Large Paper Bag"], "quantities": [50, 100, 250]}'::jsonb),
('Printed Carry Bags', 'printed-carry-bags', 'Stickers', 1200.00,
  array['Premium laminated shopping bags', 'Elegant satin cord handles', 'Glossy or matte art cardstock', 'Gold foil stamping option'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Glossy Laminated", "Premium Matte Laminated"], "quantities": [50, 100, 250]}'::jsonb),
('Courier Bags', 'courier-bags', 'Stickers', 1100.00,
  array['Tearproof tamper-proof LDPE plastic', 'Self adhesive permanent seal pod', 'Includes document pocket jacket', 'Waterproof shipping bag'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["10x12 Inch Bag", "12x16 Inch Bag"], "quantities": [100, 250, 500]}'::jsonb),
('Corrugated Boxes', 'corrugated-boxes', 'Stickers', 1400.00,
  array['Heavy-duty 3-ply brown board', 'Custom logo print layout', 'Protective shipping box', 'Shipped flat for easy storage'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["Small (8x6x4 inch)", "Medium (10x8x6 inch)"], "quantities": [50, 100, 250]}'::jsonb),
('Tuck Top Boxes', 'tuck-top-boxes', 'Stickers', 1600.00,
  array['Premium folding board boxes', 'Secure tuck-in lid closures', 'Perfect for retail cosmetic packs', 'High fidelity color rendering'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Glossy", "Premium Matte Laminated"], "quantities": [50, 100, 250]}'::jsonb),
('Soap Boxes', 'soap-boxes', 'Stickers', 900.00,
  array['Moisture resistant lamination', 'Biodegradable duplex card', 'Custom sizing available', 'Snug tuck closures'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Premium Matte Laminated"], "quantities": [100, 250, 500]}'::jsonb),
('Hang Tags', 'hang-tags', 'Stickers', 320.00,
  array['Includes pre-punched string hole', '350 GSM cardstock double sided', 'Perfect for clothing labels', 'Rounded or rectangular shape'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Matte", "Natural Kraft"], "quantities": [100, 250, 500]}'::jsonb),
('Product Labels', 'product-labels', 'Stickers', 240.00,
  array['Roll-fed quick apply labels', 'Premium water-resistant vinyl', 'Sleek custom contour shape', 'Fits jars, boxes and bottles'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"finishes": ["Standard Glossy", "Premium Matte Laminated"], "quantities": [100, 250, 500]}'::jsonb),
('Laptop Skin Labels', 'laptop-skin-labels', 'Stickers', 250.00,
  array['Premium bubble-free vinyl', 'Scratch resistant matte laminate', 'Removable leaves no sticky residue', 'Gridlines on back for easy trim'],
  array['https://images.unsplash.com/photo-1572375995501-4b0894dbe341?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["15.6 inch Laptop", "14 inch Laptop", "MacBook Pro"], "quantities": [1, 2, 5]}'::jsonb);

-- Insert Clothing, Caps & Bags
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Men''s T-Shirts', 'mens-t-shirts', 'Clothing', 350.00,
  array['100% combed cotton jersey', '180 GSM bio-washed pre-shrunk fabric', 'Premium screen or DTG branding', 'Classic crew neck fitting'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black", "White", "Navy Blue"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Women''s T-Shirts', 'womens-t-shirts', 'Clothing', 350.00,
  array['Premium soft combed cotton', 'Bio-washed lightweight fabric', 'Contoured feminine layout', 'Durable neck rib binding'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black", "White", "Baby Pink"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Polyester Tees', 'polyester-tees', 'Clothing', 250.00,
  array['100% dry-fit active polyester', 'Moisture-wicking breathable fabric', 'Sublimation printing supports bright colors', 'Ideal for sports and marathons'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Royal Blue", "Neon Green", "White"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 10, 50, 100]}'::jsonb),
('Polo T-Shirts', 'polo-t-shirts', 'Clothing', 490.00,
  array['240 GSM heavy cotton pique fabric', 'Ribbed collar and cuffs', 'High-quality chest embroidery logo', 'Side slit step bottom margins'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black", "Navy Blue", "Charcoal Gray"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Dress Shirts', 'dress-shirts', 'Clothing', 890.00,
  array['Premium cotton-poly blend oxford', 'Stiff collar and button cuffs', 'Subtle chest embroidery option', 'Iron-easy breathable weave'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Classic White", "Sky Blue"], "sizes": ["M", "L", "XL"], "quantities": [1, 5, 10]}'::jsonb),
('Embroidered Laptop Bags', 'embroidered-laptop-bags', 'Clothing', 950.00,
  array['Waterproof heavy nylon casing', 'Thick padded laptop compartment', 'Precision thread embroidery logo', 'Shoulder sling and handles included'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Midnight Black", "Steel Gray"], "quantities": [1, 5, 10, 25]}'::jsonb),
('Backpacks', 'backpacks', 'Clothing', 850.00,
  array['3 spacious zipper compartments', 'Waterbottle mesh holders', 'Branded screen print or badge', 'Padded back support and straps'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black", "Red", "Navy Blue"], "quantities": [1, 10, 25, 50]}'::jsonb),
('Tote Bags', 'tote-bags', 'Clothing', 180.00,
  array['Eco-friendly canvas cotton', 'Thick fabric handles', 'Large printable surface area', 'Reusable shopping helper'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Natural Off-White", "Black"], "quantities": [1, 10, 50, 100]}'::jsonb),
('Jute Bags', 'jute-bags', 'Clothing', 220.00,
  array['100% biodegradable golden jute', 'Laminated water-resistant interior', 'Soft cotton padded handles', 'Large size shopping bag'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Natural Brown"], "quantities": [10, 25, 50, 100]}'::jsonb),
('Sports Jersey', 'sports-jersey', 'Clothing', 400.00,
  array['Dry-fit mesh breathable polyester', 'Fully customizable name & number print', 'Sublimated side accents', 'Stretch seams for comfort'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Neon Red", "Yellow", "Blue"], "sizes": ["S", "M", "L", "XL"], "quantities": [5, 11, 20, 50]}'::jsonb),
('Embroidered Caps', 'embroidered-caps', 'Clothing', 180.00,
  array['100% cotton drill canvas fabric', 'Adjustable brass buckle back', '3D raised front embroidery logo', 'Ventilation eyelets'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black", "White", "Navy"], "quantities": [1, 10, 50, 100]}'::jsonb),
('Printed Caps', 'printed-caps', 'Clothing', 140.00,
  array['Classic 5-panel mesh back trucker cap', 'Adjustable snapback strap', 'Vivid logo print front panel', 'Ideal for outdoor staff'],
  array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black/White Mesh", "Blue/White Mesh"], "quantities": [1, 10, 50, 100]}'::jsonb;

-- Insert Mugs, Albums & Gifts
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Photo Mugs', 'photo-mugs', 'Mugs', 180.00,
  array['Premium 325ml glossy ceramic', 'Dishwasher & microwave safe', 'Vivid edge-to-edge wrap printing', 'Includes foam packing safety box'],
  array['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Classic White", "Inner Black", "Inner Red"], "quantities": [1, 2, 5, 10]}'::jsonb),
('Magic Mugs', 'magic-mugs', 'Mugs', 290.00,
  array['Thermo-reactive black coating', 'Design appears when hot liquid added', 'Premium quality ceramic', 'Fascinating surprise gift'],
  array['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Matte Black Magic"], "quantities": [1, 2, 5, 10]}'::jsonb),
('Photo Albums', 'photo-albums', 'Mugs', 750.00,
  array['Hardcover matte laminated cover', 'Thick 200 GSM photo-paper pages', 'Lay-flat binding style', '30 custom pages layout'],
  array['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["8x8 Square Album", "A4 Landscape Album"], "quantities": [1, 2, 5]}'::jsonb),
('Photo Frames', 'photo-frames', 'Mugs', 350.00,
  array['Sleek black acrylic border frame', 'Included desk stand and wall hooks', 'Gloss photo print paper inserted', 'Shatter-proof front plexiglass'],
  array['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'],
  '{"sizes": ["6x8 Inch Frame", "8x10 Inch Frame"], "quantities": [1, 2, 5, 10]}'::jsonb),
('Cushions', 'cushions', 'Mugs', 380.00,
  array['Soft velvet fabric pillow', 'Comes with microfibre cushion filling', 'Zipper bottom for easy cleaning', 'Edge-to-edge vibrant photo print'],
  array['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'],
  '{"shapes": ["Square Cushion (12x12 inch)", "Heart Shaped Cushion"], "quantities": [1, 2, 5]}'::jsonb),
('Gift Hampers', 'gift-hampers', 'Mugs', 1500.00,
  array['Curated brand gift set', 'Includes Mug, Pen, Diary, and Keychain', 'Custom printed gift box casing', 'Exceptional corporate onboarding item'],
  array['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'],
  '{"types": ["Executive Onboarding Box", "Festival Sweet Gift Set"], "quantities": [1, 5, 10, 50]}'::jsonb;

-- Insert Pens
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Customized Pens', 'customized-pens', 'Pens', 90.00,
  array['Premium laser engraving/print', 'Silver chrome pocket clip', 'Comfortable rubber grip', 'Blue ink ballpoint smooth flow'],
  array['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Matte Black", "Royal Blue"], "quantities": [25, 50, 100, 250]}'::jsonb),
('Metal Roller Pens', 'metal-roller-pens', 'Pens', 250.00,
  array['Heavy metallic body casing', 'Smooth gel roller ink refill', 'Precision gold foil name engraving', 'Elegant gift box casing included'],
  array['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Matte Black Gold", "Classic Chrome"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Plastic Ball Pens', 'plastic-ball-pens', 'Pens', 15.00,
  array['Cost-effective promo giveaway pen', 'Lightweight push button structure', 'Vivid color body prints', 'Reliable daily pen'],
  array['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Red", "Blue", "Black"], "quantities": [100, 250, 500, 1000]}'::jsonb),
('Executive Pens', 'executive-pens', 'Pens', 450.00,
  array['Premium heavy metal body', 'Luxurious writing balance', 'Engraved executive initials', 'German archival ink cartridge'],
  array['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Piano Black Lacquer", "Carbon Fiber"], "quantities": [1, 2, 5, 10]}'::jsonb),
('Premium Pens', 'premium-pens', 'Pens', 600.00,
  array['Foil accents on gunmetal frame', 'Elegant twist mechanism', 'Includes luxury leather pen pouch', 'Waterproof smudgeproof ink'],
  array['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Gunmetal Gray", "Rose Gold Trim"], "quantities": [1, 2, 5]}'::jsonb),
('Fountain Pens', 'fountain-pens', 'Pens', 800.00,
  array['Traditional gold-plated nib', 'Uses converter cartridges', 'Distinct handwriting texture', 'Classic wood gift box'],
  array['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80'],
  '{"materials": ["Premium Walnut", "Polished Steel"], "quantities": [1, 2, 5]}'::jsonb;

-- Insert Drinkware
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Sippers', 'sippers', 'Drinkware', 220.00,
  array['750ml lightweight aluminum bottle', 'Includes carabiner clip for bags', 'Wide mouth leakproof plastic cap', 'Branded wrap photo printing'],
  array['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Metallic Silver", "Matte White"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Bottles', 'bottles', 'Drinkware', 450.00,
  array['Double-walled insulated stainless steel', '12 hours hot / 24 hours cold shield', 'Premium soft matte powder coating', 'Crisp laser engraved logo'],
  array['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Matte Black", "Olive Green", "White"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Tumblers', 'tumblers', 'Drinkware', 380.00,
  array['400ml travel coffee tumbler', 'Built-in splashproof slide lid', 'Fits perfectly in car cup holders', 'Sweat-free exterior texture'],
  array['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Steel Silver", "Navy Blue"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Travel Mugs', 'travel-mugs', 'Drinkware', 320.00,
  array['Insulated travel mug with handle', 'Secure rubber base padding', 'Durable acrylic shell print', 'Convenient sip open cap'],
  array['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Red Handle", "Black Handle"], "quantities": [1, 5, 10, 50]}'::jsonb;

-- Insert Custom Polo T-shirts
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Men''s Polo', 'mens-polo', 'Polo T-shirts', 490.00,
  array['240 GSM heavy cotton pique fabric', 'Ribbed collar and cuffs', 'High-quality chest embroidery logo', 'Side slit step bottom margins'],
  array['https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Navy Blue", "Black", "Royal Blue"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Women''s Polo', 'womens-polo', 'Polo T-shirts', 490.00,
  array['Contoured ladies styling fit', 'Soft pique cotton blend fabric', 'Ribbed cuffs & premium button placket', 'Breathable anti-sweat weave'],
  array['https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Crimson Red", "White", "Black"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Premium Polo', 'premium-polo', 'Polo T-shirts', 650.00,
  array['Super-soft 100% mercerized cotton', 'Lustrous fabric finish', 'Exquisite details and thick stitching', 'Pre-shrunk colors stay bright'],
  array['https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Emerald Green", "Midnight Navy"], "sizes": ["M", "L", "XL"], "quantities": [1, 5, 10, 50]}'::jsonb),
('Sports Polo', 'sports-polo', 'Polo T-shirts', 380.00,
  array['Dry-fit polyester pique fabric', 'Breathable underarm mesh inserts', 'Durable printing support', 'Excellent for sports day and events'],
  array['https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Cobalt Blue", "Red/White Collar"], "sizes": ["S", "M", "L", "XL"], "quantities": [1, 10, 50, 100]}'::jsonb),
('Multi-location Polo', 'multi-location-polo', 'Polo T-shirts', 590.00,
  array['Branding on Chest, Sleeve, and Back', 'High-quality screen print combo', 'Heavy 220 GSM pique fabric', 'Ideal for company uniforming'],
  array['https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Black", "White"], "sizes": ["S", "M", "L", "XL"], "quantities": [10, 25, 50, 100]}'::jsonb;

-- Insert Umbrellas & Rainwear
insert into public.products (name, slug, category, base_price, features, images, options_json) values
('Custom Umbrellas', 'custom-umbrellas', 'Umbrellas', 380.00,
  array['21-inch folding auto-open frame', 'Windproof flexible fiberglass ribs', 'High-density waterproof pongee fabric', 'Branded panel screen printing'],
  array['https://images.unsplash.com/photo-1527856263669-12c3a0af2aa6?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Navy Blue", "Black", "Royal Blue/White"], "quantities": [10, 25, 50, 100]}'::jsonb),
('Raincoats', 'raincoats', 'Umbrellas', 600.00,
  array['100% waterproof heavy polyester PVC', 'Adjustable hood and button pockets', 'Reflective security strip on back', 'Logo printed front chest panel'],
  array['https://images.unsplash.com/photo-1527856263669-12c3a0af2aa6?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Navy Blue", "Neon Yellow"], "sizes": ["M", "L", "XL"], "quantities": [5, 10, 25, 50]}'::jsonb),
('Garden Umbrellas', 'garden-umbrellas', 'Umbrellas', 3200.00,
  array['Large 8-feet promo patio umbrella', 'Heavy duty iron pole mounting', 'Thick waterproof flex canopy', 'Full 4-panel branding layout'],
  array['https://images.unsplash.com/photo-1527856263669-12c3a0af2aa6?auto=format&fit=crop&w=600&q=80'],
  '{"colors": ["Red/White Panels", "Full Yellow"], "quantities": [1, 2, 5]}'::jsonb);
